### ISSUE TITLE
[Code Organization] Removal of generated files

### ISSUE THREAD

**Issue by olivierobert** [asad-u/google-search-wrapper#5]
When using Rails generators, there are many files generated on the developer's behalf in `assets/`, `test/` (for minitest), etc. If these are un-used, they should be removed.

On a related note, since RSpec is used, why not removing the `test` directory altogether?

**Comment by asad-u** [comment]
Hi @olivierobert. Thanks for the review.

There is a possibility that some of the generated files are not used when a feature is developed, but they can be used when more functionality is added on top of the base feature. For example, in the case of the typical rails generator:

![image](https://user-images.githubusercontent.com/62687519/133971152-af35882e-efce-411f-83d4-ac7d7148caff.png)

For the `model` generator, I don't think any of the files should be removed even if it's unused at that time. Specs if not added at that time, needs to be added later.

For the `controller` generator, maybe the `scss` file can be removed because FE architecture will be different for every other application.

**Comment by asad-u** [comment]
When using RSpec for tests, rails default `test` directory can be removed. Agreed 100%.

**Comment by olivierobert** [comment]
Leaving behind placeholder files does not bring much value. Over time it can become unruly as it can be hard to know which file is needed or not. The same is true for "dead code" i.e. code that is no longer used by the application. That is why when working in a team environment, keeping only the files and code that are in use at a given time is a best practice.

**Comment by asad-u** [comment]
@olivierobert This PR https://github.com/asad-u/google-search-wrapper/pull/10 addresses this issue.
